version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - /hum/:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  front:
    build: front-end
    container_name: front-end
    ports:
      - 3000:3000
    volumes:
      - /front-end:/app
    environment:
      CHOKIDAR_USEPOLLING: true
  back:
    build: back-end
    container_name: back-end
    ports:
      - 3001:3001
    volumes:
      - /back-end:/app
